### ISSUE TITLE
Mobile problem

### ISSUE THREAD

**Issue by JanickRoss** [mrf28/a2gtm#1]
It's a beautifull code example. On the web, it's perfect but on mobile, it's impossible to create card, modify text, etc. Do you plan to make mobile support for touch device ?

Thanks

**Comment by mrf28** [comment]
Hello @JanickRoss, I've actually added touch support 13 hours ago, now it's possible to create, rename and move cards and lists. Which platform did you use to test?

Since it's for portfolio purposes I don't plan to support all devices. However if it's a minor bug fix, I would'n mind fixing it.

Thanks for your feedback.

**Comment by JanickRoss** [comment]
I use chrome on android device. Galaxy S6. I'm just able to move card but if I click and existing card, I'm not able to edit text.

Thanks

**Comment by mrf28** [comment]
Well, now that's a bug. I'm using chrome on android and I don't get the same issue. I don't have access to this specific device, so I'm closing this for now and mark it as a bug.

Thanks for your feedback again.
