### ISSUE TITLE
Question - Data Model

### ISSUE THREAD

**Issue by gamefundas** [mrf28/a2gtm#6]
In the data model, any particular reason Column is not composed of cards any more? I see that originally it was the case, even the mock service indicates it, but later this was changed. Wondering if this was preferred due to performance reasons.

**Comment by mrf28** [comment]
Hello @gamefundas,

I have opted out to keep the objects decoupled. the reason, I don't store the cards into the column document, is that it's much simpler to just change the columnId into the card document. This is not a performance decision, it's more like maintainability architectural choice.

For example, when a move card action happens, the application updates just the card document (that's why the order algorithm on move). If the cards were stored within the column, the application should update both origin column, removing the card, and target column, adding the moved card.

There's a third option for this link in mongodb, that is have the card collection separated from columns, but keeping the cardId array linked to the original cards documents. So when the columns are retrieved we can include the cards objects. This way may be more performatic (i don't checked) when retrieving the columns, but it's much more of a tight coupling.

Hope I could clarify the decision making.
Best,
Marcos
